/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
import * as Query from "./Query";
export interface IEventSource {
    table?: string;
    topic?: string;
    query?: Query.IQuery;
    isCumulative?: boolean;
}
export interface IEventSourceArgs {
    table?: string;
    topic?: string;
    query?: Query.IQueryArgs;
    isCumulative?: boolean;
}
export const EventSourceCodec: thrift.IStructCodec<IEventSourceArgs, IEventSource> = {
    encode(args: IEventSourceArgs, output: thrift.TProtocol): void {
        const obj: any = {
            table: args.table,
            topic: args.topic,
            query: args.query,
            isCumulative: args.isCumulative
        };
        output.writeStructBegin("EventSource");
        if (obj.table != null) {
            output.writeFieldBegin("table", thrift.TType.STRING, 1);
            output.writeString(obj.table);
            output.writeFieldEnd();
        }
        if (obj.topic != null) {
            output.writeFieldBegin("topic", thrift.TType.STRING, 2);
            output.writeString(obj.topic);
            output.writeFieldEnd();
        }
        if (obj.query != null) {
            output.writeFieldBegin("query", thrift.TType.STRUCT, 3);
            Query.QueryCodec.encode(obj.query, output);
            output.writeFieldEnd();
        }
        if (obj.isCumulative != null) {
            output.writeFieldBegin("isCumulative", thrift.TType.BOOL, 4);
            output.writeBool(obj.isCumulative);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IEventSource {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.table = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.topic = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_3: Query.IQuery = Query.QueryCodec.decode(input);
                        _args.query = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.TType.BOOL) {
                        const value_4: boolean = input.readBool();
                        _args.isCumulative = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            table: _args.table,
            topic: _args.topic,
            query: _args.query,
            isCumulative: _args.isCumulative
        };
    }
};
export class EventSource extends thrift.StructLike implements IEventSource {
    public table?: string;
    public topic?: string;
    public query?: Query.IQuery;
    public isCumulative?: boolean;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IEventSourceArgs = {}) {
        super();
        if (args.table != null) {
            const value_5: string = args.table;
            this.table = value_5;
        }
        if (args.topic != null) {
            const value_6: string = args.topic;
            this.topic = value_6;
        }
        if (args.query != null) {
            const value_7: Query.IQuery = new Query.Query(args.query);
            this.query = value_7;
        }
        if (args.isCumulative != null) {
            const value_8: boolean = args.isCumulative;
            this.isCumulative = value_8;
        }
    }
    public static read(input: thrift.TProtocol): EventSource {
        return new EventSource(EventSourceCodec.decode(input));
    }
    public static write(args: IEventSourceArgs, output: thrift.TProtocol): void {
        return EventSourceCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return EventSourceCodec.encode(this, output);
    }
}
