/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum Operation {
    MIN = 0,
    MAX = 1,
    FIRST = 2,
    LAST = 3,
    UNIQUE_COUNT = 4,
    APPROX_UNIQUE_COUNT = 5,
    COUNT = 6,
    SUM = 7,
    AVERAGE = 8,
    VARIANCE = 9,
    SKEW = 10,
    KURTOSIS = 11,
    APPROX_PERCENTILE = 12,
    LAST_K = 13,
    FIRST_K = 14,
    TOP_K = 15,
    BOTTOM_K = 16,
    HISTOGRAM = 17,
    APPROX_HISTOGRAM_K = 18
}
