/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
import * as MetaData from "./MetaData";
export interface IStagingQuery {
    metaData?: MetaData.IMetaData;
    query?: string;
    startPartition?: string;
    setups?: Array<string>;
}
export interface IStagingQueryArgs {
    metaData?: MetaData.IMetaDataArgs;
    query?: string;
    startPartition?: string;
    setups?: Array<string>;
}
export const StagingQueryCodec: thrift.IStructCodec<IStagingQueryArgs, IStagingQuery> = {
    encode(args: IStagingQueryArgs, output: thrift.TProtocol): void {
        const obj: any = {
            metaData: args.metaData,
            query: args.query,
            startPartition: args.startPartition,
            setups: args.setups
        };
        output.writeStructBegin("StagingQuery");
        if (obj.metaData != null) {
            output.writeFieldBegin("metaData", thrift.TType.STRUCT, 1);
            MetaData.MetaDataCodec.encode(obj.metaData, output);
            output.writeFieldEnd();
        }
        if (obj.query != null) {
            output.writeFieldBegin("query", thrift.TType.STRING, 2);
            output.writeString(obj.query);
            output.writeFieldEnd();
        }
        if (obj.startPartition != null) {
            output.writeFieldBegin("startPartition", thrift.TType.STRING, 3);
            output.writeString(obj.startPartition);
            output.writeFieldEnd();
        }
        if (obj.setups != null) {
            output.writeFieldBegin("setups", thrift.TType.LIST, 4);
            output.writeListBegin(thrift.TType.STRING, obj.setups.length);
            obj.setups.forEach((value_1: string): void => {
                output.writeString(value_1);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IStagingQuery {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_2: MetaData.IMetaData = MetaData.MetaDataCodec.decode(input);
                        _args.metaData = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_3: string = input.readString();
                        _args.query = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.STRING) {
                        const value_4: string = input.readString();
                        _args.startPartition = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.TType.LIST) {
                        const value_5: Array<string> = new Array<string>();
                        const metadata_1: thrift.IThriftList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_6: string = input.readString();
                            value_5.push(value_6);
                        }
                        input.readListEnd();
                        _args.setups = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            metaData: _args.metaData,
            query: _args.query,
            startPartition: _args.startPartition,
            setups: _args.setups
        };
    }
};
export class StagingQuery extends thrift.StructLike implements IStagingQuery {
    public metaData?: MetaData.IMetaData;
    public query?: string;
    public startPartition?: string;
    public setups?: Array<string>;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IStagingQueryArgs = {}) {
        super();
        if (args.metaData != null) {
            const value_7: MetaData.IMetaData = new MetaData.MetaData(args.metaData);
            this.metaData = value_7;
        }
        if (args.query != null) {
            const value_8: string = args.query;
            this.query = value_8;
        }
        if (args.startPartition != null) {
            const value_9: string = args.startPartition;
            this.startPartition = value_9;
        }
        if (args.setups != null) {
            const value_10: Array<string> = new Array<string>();
            args.setups.forEach((value_11: string): void => {
                const value_12: string = value_11;
                value_10.push(value_12);
            });
            this.setups = value_10;
        }
    }
    public static read(input: thrift.TProtocol): StagingQuery {
        return new StagingQuery(StagingQueryCodec.decode(input));
    }
    public static write(args: IStagingQueryArgs, output: thrift.TProtocol): void {
        return StagingQueryCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return StagingQueryCodec.encode(this, output);
    }
}
