name: Test Spark module

on:
  push:
    branches:
      - main
    paths:
      - 'spark/**'
      - '.github/workflows/test_scala_spark.yaml'
      - 'build.sbt'
  pull_request:
    branches:
      - main
    paths:
      - 'spark/**'
      - '.github/workflows/test_scala_spark.yaml'
      - 'build.sbt'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  other_spark_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bazel cache credentials
        run: |
          echo "${{ secrets.BAZEL_CACHE_CREDENTIALS }}" | base64 -d > bazel-cache-key.json

      - name: Run Spark tests
        run: |
          bazel test \
            --remote_cache=https://storage.googleapis.com/zipline-bazel-cache \
            --google_credentials=bazel-cache-key.json \
            //spark:test
