name: Test Spark module on scala 2.12

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spark_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl

      - name: Run Other Spark tests
        run: |
          ./mill spark.test.testOnly "ai.chronon.spark.test.other.*"

  batch_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl

      - name: Run Batch tests
        run: |
          ./mill spark.test.testOnly "ai.chronon.spark.test.batch.*"

  fetcher_tests:
    runs-on: ubuntu_32_core_128gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl

      - name: Run Fetcher tests
        run: |
          ./mill spark.test.testOnly "ai.chronon.spark.test.fetcher.*"

  join_tests:
    runs-on: ubuntu_32_core_128gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl

      - name: Run Join tests
        run: |
          ./mill spark.test.testOnly "ai.chronon.spark.test.join.*"

  groupby_tests:
    runs-on: ubuntu_32_core_128gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl

      - name: Run GroupBy tests
        run: |
          ./mill spark.test.testOnly "ai.chronon.spark.test.groupby.*"

  analyzer_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl

      - name: Run Analyzer tests
        run: |
          ./mill spark.test.testOnly "ai.chronon.spark.test.analyzer.*" "ai.chronon.spark.test.bootstrap.*"

  streaming_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl

      - name: Run Streaming tests
        run: |
          ./mill spark.test.testOnly "ai.chronon.spark.test.streaming.*"

  kv_store_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl

      - name: Run KV Store tests
        run: |
          ./mill spark.test.testOnly "ai.chronon.spark.test.kv_store.*"

  udafs_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl

      - name: Run UDAFs tests
        run: |
          ./mill spark.test.testOnly "ai.chronon.spark.test.udafs.*"

  stats_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl

      - name: Run Stats tests
        run: |
          ./mill spark.test.testOnly "ai.chronon.spark.test.stats.*"
