name: Test Scala and Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python virtual environment
        run: |
          python3 -m venv chronon_py_env
          source chronon_py_env/bin/activate

      - name: Run Chronon Python lint
        run: |
          source chronon_py_env/bin/activate
          cd api/py/ai/chronon
          pip install importlib-metadata==4.11.4
          pip install flake8
          flake8 --extend-ignore=W605,Q000,F631

      - name: Run Chronon Python tests
        run: |
          source chronon_py_env/bin/activate
          thrift --gen py -out api/py/ai/chronon api/thrift/api.thrift
          cd api/py
          pip install -r requirements/dev.txt
          pip install tox
          tox

      - uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: api/py/htmlcov

  spark_scala_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4
      - name: Run scala tests
        run: |
          export SBT_OPTS="-Xmx8G -Xms2G -J--add-opens=java.base/sun.nio.ch=ALL-UNNAMED"
          sbt spark_uber/test


  non_spark_scala_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Run ScalafmtCheck
        run: sbt +scalafmtCheck

      - name: Run Flink tests
        run: |
          export SBT_OPTS="-Xmx8G -Xms2G"
          sbt "++ 2.12.18 flink/test"

      - name: Run Aggregator tests
        run: |
          export SBT_OPTS="-Xmx8G -Xms2G"
          sbt "++ 2.12.18 aggregator/test"

      - name: Run Online tests
        run: |
          export SBT_OPTS="-Xmx8G -Xms2G"
          sbt "++ 2.12.18 online/test"

      - name: Run api tests
        run: |
          export SBT_OPTS="-Xmx8G -Xms2G"
          sbt "++ 2.12.18 api/test"