name: Test Spark module on scala 2.12

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spark_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Spark tests
        run: |
          bazel test \
            --test_env=JAVA_OPTS="-Xmx8G -Xms2G" \
            //spark:tests

  batch_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Batch tests
        run: |
          bazel test \
            --test_env=JAVA_OPTS="-Xmx8G -Xms2G" \
            //spark:batch_test

  fetcher_tests:
    runs-on: ubuntu_32_core_128gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Fetcher tests
        run: |
          bazel test \
            --test_env=JAVA_OPTS="-Xmx16G -Xms8G" \
            //spark:fetcher_test

  join_tests:
    runs-on: ubuntu_32_core_128gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Join tests
        run: |
          bazel test \
            --test_env=JAVA_OPTS="-Xmx16G -Xms8G" \
            //spark:join_test

  groupby_tests:
    runs-on: ubuntu_32_core_128gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Run GroupBy tests
        run: |
          bazel test \
            --test_env=JAVA_OPTS="-Xmx16G -Xms8G" \
            //spark:groupby_test

  analyzer_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Analyzer tests
        run: |
          bazel test \
            --test_env=JAVA_OPTS="-Xmx16G -Xms8G" \
            //spark:analyzer_test

  streaming_tests:
    runs-on: ubuntu-8_cores-32_gb
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Streaming tests
        run: |
          bazel test \
            --test_env=JAVA_OPTS="-Xmx16G -Xms8G" \
            //spark:streaming_test
