name: Trigger Subtree Update in Platform

on:
  push:
    branches: [ main ]  # Run when changes land in chronon's main

jobs:
  trigger-subtree-pull:
    uses: zipline-ai/platform/.github/workflows/subtree_pull_reusable.yaml@main
    secrets: inherit  # Passes all secrets (needed for the deploy key)